### ISSUE TITLE
Error: Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by sazzer** [zkamil/ramlo#13]
I've just installed Ramlo on my OSX machine, fixed up the line endings (Issue #5), and then running it gives the error:

```
> ramlo
module.js:442
    throw err;
    ^

Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/coxg/.nvm/versions/node/v6.3.0/lib/node_modules/ramlo/bin/ramlo.js:10:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I can fix this locally by installing node-sass into my ~/.nvm/versions/node/v6.3.0/lib/node_modules directory, but I assume the real problem is that it's not declared in the ramlo package.json file.

**Comment by kamilzasada** [comment]
I've just pushed to npm new version - v0.2.1. It should resolve your problem. I moved _node-sass_ from _dependencies_ to _devDependencies_, but forgot to remove _require_ statement in my script.
