### ISSUE TITLE
TypeError: body.schemaContent is not a function

### ISSUE THREAD

**Issue by adanieljsinclair** [zkamil/ramlo#14]
After working past the node-sass issue, I got this, which I worked around by checking the reference in the source. I'm not sure what would cause this?

C:\Program Files\nodejs\node_modules\ramlo\src\modules\api.js:281
                var sch = body.schemaContent();
                               ^

TypeError: body.schemaContent is not a function
    at C:\Program Files\nodejs\node_modules\ramlo\src\modules\api.js:281:32
    at arrayEach (C:\Program Files\nodejs\node_modules\ramlo\node_modules\lodash\lodash.js:451:11)
    at Function.forEach (C:\Program Files\nodejs\node_modules\ramlo\node_modules\lodash\lodash.js:8634:14)
    at C:\Program Files\nodejs\node_modules\ramlo\src\modules\api.js:278:15
    at arrayEach (C:\Program Files\nodejs\node_modules\ramlo\node_modules\lodash\lodash.js:451:11)
    at Function.forEach (C:\Program Files\nodejs\node_modules\ramlo\node_modules\lodash\lodash.js:8634:14)
    at produceResponseBody (C:\Program Files\nodejs\node_modules\ramlo\src\modules\api.js:273:7)
    at C:\Program Files\nodejs\node_modules\ramlo\src\modules\api.js:99:27
    at arrayEach (C:\Program Files\nodejs\node_modules\ramlo\node_modules\lodash\lodash.js:451:11)
    at Function.forEach (C:\Program Files\nodejs\node_modules\ramlo\node_modules\lodash\lodash.js:8634:14)

**Comment by shilov** [comment]
Bumped into a similar issue:

```
/usr/local/lib/node_modules/ramlo/src/modules/api.js:246
    if (Object.keys(ramlBody).length > 0 && _.isFunction(body.schemaContent)) {
                                                         ^

ReferenceError: body is not defined
    at produceRequestBody (/usr/local/lib/node_modules/ramlo/src/modules/api.js:246:58)
    at /usr/local/lib/node_modules/ramlo/src/modules/api.js:98:26
    at arrayEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:9011:14)
    at produceEndpoints (/usr/local/lib/node_modules/ramlo/src/modules/api.js:81:7)
    at /usr/local/lib/node_modules/ramlo/src/modules/api.js:66:42
    at arrayEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:9011:14)
    at produceResources (/usr/local/lib/node_modules/ramlo/src/modules/api.js:45:7)
    at module.exports (/usr/local/lib/node_modules/ramlo/src/modules/api.js:688:26)
```
