### ISSUE TITLE
Issue when declaring request body

### ISSUE THREAD

**Issue by prvdph** [zkamil/ramlo#15]
**ramlo 0.2.1**

> C:\bin\nvm\v6.2.1\node_modules\ramlo\src\modules\api.js:246
>     if (Object.keys(ramlBody).length > 0 && _.isFunction(body.schemaContent)) {
> 
> ReferenceError: body is not defined

It should be `_.isFunction(ramlBody.schemaContent)` not `_.isFunction(body.schemaContent)`

**Comment by derlin** [comment]
I have the same problem: 

```
ramlo/src/modules/api.js:246
    if (Object.keys(ramlBody).length > 0 && _.isFunction(body.schemaContent)) {
                                                         ^

ReferenceError: body is not defined
    at produceRequestBody (/tmp/ramlo/src/modules/api.js:246:58)
    at /tmp/ramlo/src/modules/api.js:98:26
    at arrayEach (/tmp/ramlo/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/tmp/ramlo/node_modules/lodash/lodash.js:9011:14)
    at produceEndpoints (/tmp/ramlo/src/modules/api.js:81:7)
    at /tmp/ramlo/src/modules/api.js:66:42
    at arrayEach (/tmp/ramlo/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/tmp/ramlo/node_modules/lodash/lodash.js:9011:14)
    at produceResources (/tmp/ramlo/src/modules/api.js:45:7)
    at module.exports (/tmp/ramlo/src/modules/api.js:688:26)
```

**Comment by freddrake** [comment]
I think this is the same as issue #26, which was fixed in PR #23, but has not been released.
