### ISSUE TITLE
TypeError: parameter.repeat is not a function

### ISSUE THREAD

**Issue by ppattersonenvista** [zkamil/ramlo#21]
starting ramlo...
loading dependencies...

creating documentation...
/usr/local/lib/node_modules/ramlo/src/modules/api.js:231
            repeat: parameter.repeat()
                              ^

TypeError: parameter.repeat is not a function
    at /usr/local/lib/node_modules/ramlo/src/modules/api.js:231:31
    at arrayEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:9011:14)
    at produceQueryParameters (/usr/local/lib/node_modules/ramlo/src/modules/api.js:170:7)
    at /usr/local/lib/node_modules/ramlo/src/modules/api.js:97:30
    at arrayEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:9011:14)
    at produceEndpoints (/usr/local/lib/node_modules/ramlo/src/modules/api.js:81:7)
    at /usr/local/lib/node_modules/ramlo/src/modules/api.js:66:42
    at arrayEach (/usr/local/lib/node_modules/ramlo/node_modules/lodash/lodash.js:522:11)

**Comment by ppattersonenvista** [comment]
This issue is fixed with the following pull request

commit ab778396cb1c2eea654292ba17876147da4d12e9

**Comment by ulaBLUE** [comment]
Hi,
I get this issue with current version. It is blocker issuer as I cannot run raml files written 1.0. 
Can you please let me know when is the plan to release ? Thanks

**Comment by vglushonkov** [comment]
When is this expected to release?
