### ISSUE TITLE
body is not defined

### ISSUE THREAD

**Issue by pickworth** [zkamil/ramlo#22]
nathan@mypc:~/MYAPP/server/api/spec$ ramlo -f api.raml 

```
starting ramlo...
loading dependencies...
[ramlo_dependencies]: 1476.154ms
creating documentation...
/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/src/modules/api.js:246
    if (Object.keys(ramlBody).length > 0 && _.isFunction(body.schemaContent)) {
                                                         ^

ReferenceError: body is not defined
    at produceRequestBody (/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/src/modules/api.js:246:58)
    at /home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/src/modules/api.js:98:26
    at arrayEach (/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/node_modules/lodash/lodash.js:9011:14)
    at produceEndpoints (/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/src/modules/api.js:81:7)
    at /home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/src/modules/api.js:66:42
    at arrayEach (/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/node_modules/lodash/lodash.js:9011:14)
    at produceResources (/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/src/modules/api.js:45:7)
    at module.exports (/home/nathan/.nvm/versions/node/v6.2.0/lib/node_modules/ramlo/src/modules/api.js:688:26)
```

**Comment by pickworth** [comment]
i see this is fixed via PR #18

Thanks @nickburns2006
